### PR TITLE
Adding support for Anthropic, Palm, AI21, Aleph Alpha, TogetherAI,

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hi @lindiatjuatja, 

Saw you support OpenAI, Azure, Cohere and HF.  I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and was wondering if we could be helpful.

I added support for the providers listed above by replacing the chatcompletion.acreate with acompletion. The code is pretty similar to the OpenAI class - as litellm follows the same pattern as the openai-python sdk.

Would love to know if this helps.

Happy to add additional tests / update documentation, if the initial PR looks good to you.

### CODE REVIEW

**Review by neubig — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution! This looks like a nice addition, but I think instead of changing `openai_provider.py`, it'd be good to create a new file `litellm_provider.py` that mirrors `openai_provider.py`. This would stress the fact that litelllm isn't limited to just calling openai.

**Comment by krrishdholakia** [comment]
Hey @neubig will do.  Thanks for the feedback!

**Comment by krrishdholakia** [comment]
Updated based on change requested by @neubig, let me know if there's any other blockers

**Review by neubig — COMMENTED** [review]
OK, I went through and did some fixes. I'm now a co-author so if @cabreraalex could take a quick look for a review that'd be ideal.

**Review by neubig — APPROVED** [review]

**Comment by cabreraalex** [comment]
This looks awesome thanks so much!!

**Comment by krrishdholakia** [comment]
Thanks for the merge. Here's how to test how the new models are working: https://docs.litellm.ai/docs/proxy_api#step-2-test-a-new-llm

**Pull request merged**
