### PR TITLE
Add [google-cloud, gpt-3.5-turbo-0301,  gpt-4-0314] to analysis_gpt_mt

### PR DESCRIPTION
**Pull request by zwhe99**
# Description
This PR adds system outputs of [google-cloud, gpt-3.5-turbo-0301,  gpt-4-0314] to MT analysis example. 
- I put the new system output in my fork of gpt-MT (https://github.com/zwhe99/gpt-MT).
- Add new systems in `examples/analysis_gpt_mt/config.py`
- Update the `examples/analysis_gpt_mt/README.md`

# References
- #128 
- [Twitter](https://twitter.com/gneubig/status/1668626459362234376?s=20)

### CODE REVIEW

**Comment by zwhe99** [comment]
@neubig https://github.com/zwhe99/gpt-MT also has outputs of DeepL. However, DeepL does not support en<->ha and en<->is. I'm not sure how to handle a situation where a system only supports partial language pairs

**Comment by neubig** [comment]
Thanks a bunch @zwhe99! I'll take a look and play around with this now.

To answer your question, it's already possible to create slices for each language pair to investigate accuracy be language pair separately, and we could create a slice "DeepL Supported Language Pairs" for the average over all language pairs that DeepL supports as well.

**Review by neubig — APPROVED** [review]
Looks great! This runs for me locally, and I just fixed a few small formatting things and gave you more credit :) I'll merge this in.

**Comment by zwhe99** [comment]
Thank you! I hope this helps the community!

**Pull request merged**
