### PR TITLE
feat: add alpaca data

### PR DESCRIPTION
**Pull request by cabreraalex**

### CODE REVIEW

**Review by neubig — CHANGES_REQUESTED** [review]
This dataset is too big to commit to the repo. Let's put it somewhere and give instructions to download it.

**Comment by cabreraalex** [comment]
Good point, removed!

**Review by neubig — APPROVED** [review]
This looks OK, but I'd prefer a slight bit more explanation about what kind of data it is, even just a paragraph or so.

**Comment by Sparkier** [comment]
Also, we should probably make it a habit to add any of these to zenoml.com docs whenever we add stuff to zeno-build.

**Pull request merged**
